// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricStatus int32

const (
	MetricStatus_STATUS_UNSPECIFIED       MetricStatus = 0
	MetricStatus_STATUS_OK                MetricStatus = 1
	MetricStatus_STATUS_PARSE_ERROR       MetricStatus = 2
	MetricStatus_STATUS_PERMISSION_DENIED MetricStatus = 3
)

// Enum value maps for MetricStatus.
var (
	MetricStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_PARSE_ERROR",
		3: "STATUS_PERMISSION_DENIED",
	}
	MetricStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED":       0,
		"STATUS_OK":                1,
		"STATUS_PARSE_ERROR":       2,
		"STATUS_PERMISSION_DENIED": 3,
	}
)

func (x MetricStatus) Enum() *MetricStatus {
	p := new(MetricStatus)
	*p = x
	return p
}

func (x MetricStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[0].Descriptor()
}

func (MetricStatus) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[0]
}

func (x MetricStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricStatus.Descriptor instead.
func (MetricStatus) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceId  string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix epoch milliseconds (UTC)
	Status    MetricStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=telemetry.v1.MetricStatus" json:"status,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Metric_Cpu
	//	*Metric_Memory
	//	*Metric_Network
	//	*Metric_Tcp
	Payload       isMetric_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Metric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metric) GetStatus() MetricStatus {
	if x != nil {
		return x.Status
	}
	return MetricStatus_STATUS_UNSPECIFIED
}

func (x *Metric) GetPayload() isMetric_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Metric) GetCpu() *CpuMetric {
	if x != nil {
		if x, ok := x.Payload.(*Metric_Cpu); ok {
			return x.Cpu
		}
	}
	return nil
}

func (x *Metric) GetMemory() *MemoryMetric {
	if x != nil {
		if x, ok := x.Payload.(*Metric_Memory); ok {
			return x.Memory
		}
	}
	return nil
}

func (x *Metric) GetNetwork() *NetworkMetric {
	if x != nil {
		if x, ok := x.Payload.(*Metric_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *Metric) GetTcp() *TcpMetric {
	if x != nil {
		if x, ok := x.Payload.(*Metric_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

type isMetric_Payload interface {
	isMetric_Payload()
}

type Metric_Cpu struct {
	Cpu *CpuMetric `protobuf:"bytes,10,opt,name=cpu,proto3,oneof"`
}

type Metric_Memory struct {
	Memory *MemoryMetric `protobuf:"bytes,11,opt,name=memory,proto3,oneof"`
}

type Metric_Network struct {
	Network *NetworkMetric `protobuf:"bytes,12,opt,name=network,proto3,oneof"`
}

type Metric_Tcp struct {
	Tcp *TcpMetric `protobuf:"bytes,13,opt,name=tcp,proto3,oneof"` // Phase 6: eBPF TCP tracepoint events
}

func (*Metric_Cpu) isMetric_Payload() {}

func (*Metric_Memory) isMetric_Payload() {}

func (*Metric_Network) isMetric_Payload() {}

func (*Metric_Tcp) isMetric_Payload() {}

type CpuMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent  float32                `protobuf:"fixed32,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"` // 0.0 - 100.0
	LoadAvg_1M    float32                `protobuf:"fixed32,2,opt,name=load_avg_1m,json=loadAvg1m,proto3" json:"load_avg_1m,omitempty"`
	LoadAvg_5M    float32                `protobuf:"fixed32,3,opt,name=load_avg_5m,json=loadAvg5m,proto3" json:"load_avg_5m,omitempty"`
	LoadAvg_15M   float32                `protobuf:"fixed32,4,opt,name=load_avg_15m,json=loadAvg15m,proto3" json:"load_avg_15m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetric) Reset() {
	*x = CpuMetric{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetric) ProtoMessage() {}

func (x *CpuMetric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetric.ProtoReflect.Descriptor instead.
func (*CpuMetric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *CpuMetric) GetUsagePercent() float32 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CpuMetric) GetLoadAvg_1M() float32 {
	if x != nil {
		return x.LoadAvg_1M
	}
	return 0
}

func (x *CpuMetric) GetLoadAvg_5M() float32 {
	if x != nil {
		return x.LoadAvg_5M
	}
	return 0
}

func (x *CpuMetric) GetLoadAvg_15M() float32 {
	if x != nil {
		return x.LoadAvg_15M
	}
	return 0
}

type MemoryMetric struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalKb          uint64                 `protobuf:"varint,1,opt,name=total_kb,json=totalKb,proto3" json:"total_kb,omitempty"`
	AvailableKb      uint64                 `protobuf:"varint,2,opt,name=available_kb,json=availableKb,proto3" json:"available_kb,omitempty"`
	UsedKb           uint64                 `protobuf:"varint,3,opt,name=used_kb,json=usedKb,proto3" json:"used_kb,omitempty"`
	UsagePercent     float32                `protobuf:"fixed32,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	SwapTotalKb      uint64                 `protobuf:"varint,10,opt,name=swap_total_kb,json=swapTotalKb,proto3" json:"swap_total_kb,omitempty"`
	SwapFreeKb       uint64                 `protobuf:"varint,11,opt,name=swap_free_kb,json=swapFreeKb,proto3" json:"swap_free_kb,omitempty"`
	SwapUsagePercent float32                `protobuf:"fixed32,12,opt,name=swap_usage_percent,json=swapUsagePercent,proto3" json:"swap_usage_percent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemoryMetric) Reset() {
	*x = MemoryMetric{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetric) ProtoMessage() {}

func (x *MemoryMetric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetric.ProtoReflect.Descriptor instead.
func (*MemoryMetric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryMetric) GetTotalKb() uint64 {
	if x != nil {
		return x.TotalKb
	}
	return 0
}

func (x *MemoryMetric) GetAvailableKb() uint64 {
	if x != nil {
		return x.AvailableKb
	}
	return 0
}

func (x *MemoryMetric) GetUsedKb() uint64 {
	if x != nil {
		return x.UsedKb
	}
	return 0
}

func (x *MemoryMetric) GetUsagePercent() float32 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *MemoryMetric) GetSwapTotalKb() uint64 {
	if x != nil {
		return x.SwapTotalKb
	}
	return 0
}

func (x *MemoryMetric) GetSwapFreeKb() uint64 {
	if x != nil {
		return x.SwapFreeKb
	}
	return 0
}

func (x *MemoryMetric) GetSwapUsagePercent() float32 {
	if x != nil {
		return x.SwapUsagePercent
	}
	return 0
}

type NetworkMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	RxBytesPerSec uint64                 `protobuf:"varint,2,opt,name=rx_bytes_per_sec,json=rxBytesPerSec,proto3" json:"rx_bytes_per_sec,omitempty"`
	TxBytesPerSec uint64                 `protobuf:"varint,3,opt,name=tx_bytes_per_sec,json=txBytesPerSec,proto3" json:"tx_bytes_per_sec,omitempty"`
	RxErrors      uint64                 `protobuf:"varint,10,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors      uint64                 `protobuf:"varint,11,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	RxDropped     uint64                 `protobuf:"varint,12,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"`
	TxDropped     uint64                 `protobuf:"varint,13,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetric) Reset() {
	*x = NetworkMetric{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetric) ProtoMessage() {}

func (x *NetworkMetric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetric.ProtoReflect.Descriptor instead.
func (*NetworkMetric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkMetric) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkMetric) GetRxBytesPerSec() uint64 {
	if x != nil {
		return x.RxBytesPerSec
	}
	return 0
}

func (x *NetworkMetric) GetTxBytesPerSec() uint64 {
	if x != nil {
		return x.TxBytesPerSec
	}
	return 0
}

func (x *NetworkMetric) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *NetworkMetric) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *NetworkMetric) GetRxDropped() uint64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *NetworkMetric) GetTxDropped() uint64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

type TcpMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	SrcAddr       string                 `protobuf:"bytes,2,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	DstAddr       string                 `protobuf:"bytes,3,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	OldState      string                 `protobuf:"bytes,6,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState      string                 `protobuf:"bytes,7,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Comm          string                 `protobuf:"bytes,8,opt,name=comm,proto3" json:"comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpMetric) Reset() {
	*x = TcpMetric{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpMetric) ProtoMessage() {}

func (x *TcpMetric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpMetric.ProtoReflect.Descriptor instead.
func (*TcpMetric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *TcpMetric) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TcpMetric) GetSrcAddr() string {
	if x != nil {
		return x.SrcAddr
	}
	return ""
}

func (x *TcpMetric) GetDstAddr() string {
	if x != nil {
		return x.DstAddr
	}
	return ""
}

func (x *TcpMetric) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *TcpMetric) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TcpMetric) GetOldState() string {
	if x != nil {
		return x.OldState
	}
	return ""
}

func (x *TcpMetric) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *TcpMetric) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

type Ack struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MetricsReceived int64                  `protobuf:"varint,3,opt,name=metrics_received,json=metricsReceived,proto3" json:"metrics_received,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ack) GetMetricsReceived() int64 {
	if x != nil {
		return x.MetricsReceived
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ftelemetry.v1\"\xcb\x02\n" +
	"\x06Metric\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.telemetry.v1.MetricStatusR\x06status\x12+\n" +
	"\x03cpu\x18\n" +
	" \x01(\v2\x17.telemetry.v1.CpuMetricH\x00R\x03cpu\x124\n" +
	"\x06memory\x18\v \x01(\v2\x1a.telemetry.v1.MemoryMetricH\x00R\x06memory\x127\n" +
	"\anetwork\x18\f \x01(\v2\x1b.telemetry.v1.NetworkMetricH\x00R\anetwork\x12+\n" +
	"\x03tcp\x18\r \x01(\v2\x17.telemetry.v1.TcpMetricH\x00R\x03tcpB\t\n" +
	"\apayload\"\x92\x01\n" +
	"\tCpuMetric\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x02R\fusagePercent\x12\x1e\n" +
	"\vload_avg_1m\x18\x02 \x01(\x02R\tloadAvg1m\x12\x1e\n" +
	"\vload_avg_5m\x18\x03 \x01(\x02R\tloadAvg5m\x12 \n" +
	"\fload_avg_15m\x18\x04 \x01(\x02R\n" +
	"loadAvg15m\"\xfe\x01\n" +
	"\fMemoryMetric\x12\x19\n" +
	"\btotal_kb\x18\x01 \x01(\x04R\atotalKb\x12!\n" +
	"\favailable_kb\x18\x02 \x01(\x04R\vavailableKb\x12\x17\n" +
	"\aused_kb\x18\x03 \x01(\x04R\x06usedKb\x12#\n" +
	"\rusage_percent\x18\x04 \x01(\x02R\fusagePercent\x12\"\n" +
	"\rswap_total_kb\x18\n" +
	" \x01(\x04R\vswapTotalKb\x12 \n" +
	"\fswap_free_kb\x18\v \x01(\x04R\n" +
	"swapFreeKb\x12,\n" +
	"\x12swap_usage_percent\x18\f \x01(\x02R\x10swapUsagePercent\"\x80\x02\n" +
	"\rNetworkMetric\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12'\n" +
	"\x10rx_bytes_per_sec\x18\x02 \x01(\x04R\rrxBytesPerSec\x12'\n" +
	"\x10tx_bytes_per_sec\x18\x03 \x01(\x04R\rtxBytesPerSec\x12\x1b\n" +
	"\trx_errors\x18\n" +
	" \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\v \x01(\x04R\btxErrors\x12\x1d\n" +
	"\n" +
	"rx_dropped\x18\f \x01(\x04R\trxDropped\x12\x1d\n" +
	"\n" +
	"tx_dropped\x18\r \x01(\x04R\ttxDropped\"\xd7\x01\n" +
	"\tTcpMetric\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x19\n" +
	"\bsrc_addr\x18\x02 \x01(\tR\asrcAddr\x12\x19\n" +
	"\bdst_addr\x18\x03 \x01(\tR\adstAddr\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x12\x1b\n" +
	"\told_state\x18\x06 \x01(\tR\boldState\x12\x1b\n" +
	"\tnew_state\x18\a \x01(\tR\bnewState\x12\x12\n" +
	"\x04comm\x18\b \x01(\tR\x04comm\"d\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10metrics_received\x18\x03 \x01(\x03R\x0fmetricsReceived*k\n" +
	"\fMetricStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x16\n" +
	"\x12STATUS_PARSE_ERROR\x10\x02\x12\x1c\n" +
	"\x18STATUS_PERMISSION_DENIED\x10\x032N\n" +
	"\x10TelemetryService\x12:\n" +
	"\rStreamMetrics\x12\x14.telemetry.v1.Metric\x1a\x11.telemetry.v1.Ack(\x01B:Z8github.com/Yahia995/edge-telemetry/agent/proto/telemetryb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_telemetry_proto_goTypes = []any{
	(MetricStatus)(0),     // 0: telemetry.v1.MetricStatus
	(*Metric)(nil),        // 1: telemetry.v1.Metric
	(*CpuMetric)(nil),     // 2: telemetry.v1.CpuMetric
	(*MemoryMetric)(nil),  // 3: telemetry.v1.MemoryMetric
	(*NetworkMetric)(nil), // 4: telemetry.v1.NetworkMetric
	(*TcpMetric)(nil),     // 5: telemetry.v1.TcpMetric
	(*Ack)(nil),           // 6: telemetry.v1.Ack
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.Metric.status:type_name -> telemetry.v1.MetricStatus
	2, // 1: telemetry.v1.Metric.cpu:type_name -> telemetry.v1.CpuMetric
	3, // 2: telemetry.v1.Metric.memory:type_name -> telemetry.v1.MemoryMetric
	4, // 3: telemetry.v1.Metric.network:type_name -> telemetry.v1.NetworkMetric
	5, // 4: telemetry.v1.Metric.tcp:type_name -> telemetry.v1.TcpMetric
	1, // 5: telemetry.v1.TelemetryService.StreamMetrics:input_type -> telemetry.v1.Metric
	6, // 6: telemetry.v1.TelemetryService.StreamMetrics:output_type -> telemetry.v1.Ack
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	file_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*Metric_Cpu)(nil),
		(*Metric_Memory)(nil),
		(*Metric_Network)(nil),
		(*Metric_Tcp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
